#!/bin/bash
#This is a test script to setup my cloud server to be ready for docker

cd ~

yum install -y yum-utils device-mapper-persistent-data lvm2

yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo

yum install docker-ce -y --allowerasing

systemctl enable docker

systemctl start docker

mkdir onboarding

touch ~/onboarding/dockerfile

cp ~/Scripttrial/dockerfile ~/onboarding/dockerfile
